version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/davebream/mcpl/cmd.version={{.Version}}
      - -X github.com/davebream/mcpl/cmd.commit={{.ShortCommit}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: davebream
      name: homebrew-tap
    homepage: https://github.com/davebream/mcpl
    description: Shared MCP server launcher
    license: MIT

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
